// 集中管理 DOM 元素引用。
const $ = (id) => document.getElementById(id);

export const els = {
  dayValue: $("dayValue"),
  stageName: $("stageName"),
  stageTheme: $("stageTheme"),
  stageProgress: $("stageProgress"),
  metrics: $("metrics"),
  windText: $("windText"),
  phaseNote: $("phaseNote"),
  card: $("card"),
  cardType: $("cardType"),
  cardCost: $("cardCost"),
  cardTitle: $("cardTitle"),
  cardSource: $("cardSource"),
  cardText: $("cardText"),
  cardTags: $("cardTags"),
  effectPreview: $("effectPreview"),
  leftHint: $("leftHint"),
  rightHint: $("rightHint"),
  leftLabel: $("leftLabel"),
  rightLabel: $("rightLabel"),
  leftBtn: $("leftBtn"),
  rightBtn: $("rightBtn"),
  historyList: $("historyList"),
  newGameBtn: $("newGameBtn"),
  continueBtn: $("continueBtn"),
  helpBtn: $("helpBtn"),
  preciseToggle: $("preciseToggle"),
  autosaveToggle: $("autosaveToggle"),
  modal: $("modal"),
  modalTitle: $("modalTitle"),
  modalBody: $("modalBody"),
  modalClose: $("modalClose"),
  modalPrimary: $("modalPrimary"),
};
