(function () {
  const c = (id, stage, type, title, source, text, left, right, tags = [], once = true, extra = {}) => ({
    id,
    stage,
    type,
    title,
    source,
    text,
    left,
    right,
    tags,
    once,
    ...extra,
  });

  const e = (label, effects, cost = 1, hint = "", extra = {}) => ({ label, effects, cost, hint, ...extra });

  window.GAME_DATA = {
    stats: {
      council: { name: "元老院", desc: "内部支持、部门协同、派系容忍度" },
      people: { name: "民望", desc: "归化民、村社、工匠与周边社会的接受度" },
      military: { name: "军务", desc: "保卫、纪律、治安、武装威慑" },
      livelihood: { name: "生计", desc: "粮食、物资、卫生、工程与生产能力" },
    },
    initialState: {
      day: 1,
      stats: { council: 50, people: 50, military: 50, livelihood: 50 },
      wind: 15,
    },
    stages: [
      { id: "landing", name: "登陆阶段", start: 1, end: 15, theme: "卸载、安营、清点、第一接触", note: "先把队伍和物资安顿下来。任何急躁都会留下痕迹。" },
      { id: "foothold", name: "立足阶段", start: 16, end: 40, theme: "开荒、住房、卫生、规则", note: "临时营地必须变成据点，外部社会也开始观察你。" },
      { id: "build", name: "初期建设阶段", start: 41, end: 70, theme: "工坊、码头、制度、劳力", note: "生产体系开始长出骨架，内部路线争执也会变得尖锐。" },
      { id: "stable", name: "稳定阶段", start: 71, end: 100, theme: "外部试探、路线成型、百日总结", note: "百日开局进入审视期，四柱短板都会被放大。" },
    ],
    reports: {
      landing: {
        title: "登陆阶段报告",
        text: "船队靠岸，博铺与百仞滩之间的一切都还只是临时安排。文德嗣必须先让人、货、枪和规矩都落地。",
      },
      foothold: {
        title: "立足阶段报告",
        text: "登陆后的慌乱逐渐退去，营地开始有了日常。外部村社、俘虏、工匠和县城的视线，也正一点点靠近。",
      },
      build: {
        title: "初期建设阶段报告",
        text: "工坊、道路、农庄和制度改革一并涌来。临高不再只是临时营地，而开始像一种新秩序。",
      },
      stable: {
        title: "稳定阶段报告",
        text: "第一轮外部试探已经出现。百日将近，执委会要的不只是活下来，还要知道自己会变成什么。",
      },
    },
    endings: [
      { id: "exposed", title: "过早暴露", test: s => s.wind >= 100, text: "临高的异常太快传了出去。官府、士绅和海上势力同时把目光转向这里，百日开局被迫进入外部危机。" },
      { id: "council_low", title: "被架空的裁断者", test: s => s.stats.council <= 0, text: "元老院已经不愿继续授予文德嗣临时裁断权。会议、部门和派系重新接管局面，百日计划失去速度。" },
      { id: "council_high", title: "会议吞没百日", test: s => s.stats.council >= 100, text: "每个部门都得到了安抚，每个元老都有理由发言。代价是裁断变慢，资源被内部需求切碎。" },
      { id: "people_low", title: "周边离心", test: s => s.stats.people <= 0, text: "村社、劳工和归化民开始用沉默、逃亡和告密回应临高。新秩序还没站稳，就已经失去了外部土壤。" },
      { id: "people_high", title: "让利失度", test: s => s.stats.people >= 100, text: "外部关系表面和顺，但规矩被反复讨价还价。执委会认为文德嗣过于软弱，临高权威被稀释。" },
      { id: "military_low", title: "营地失控", test: s => s.stats.military <= 0, text: "警戒、纪律和武备都没有形成可靠秩序。偷盗、冲突和外部试探接连发生，百日开局被安全危机击穿。" },
      { id: "military_high", title: "军管阴影", test: s => s.stats.military >= 100, text: "营地确实安静了，但那是恐惧带来的安静。元老院和民众都开始怀疑，这是否仍是共同事业。" },
      { id: "livelihood_low", title: "生计崩盘", test: s => s.stats.livelihood <= 0, text: "粮食、药品、住房和工程一起告急。没有任何路线能越过基本生存，百日开局失败。" },
      { id: "livelihood_high", title: "生产压倒一切", test: s => s.stats.livelihood >= 100, text: "工坊和工程飞快推进，却把人力、补给和耐心都压到极限。临高像机器一样运转，也像机器一样磨损所有人。" },
    ],
    successEndings: [
      { id: "steady", title: "稳健立足", text: "四柱都没有失衡，风声仍可控制。文德嗣交出了一份不耀眼但扎实的百日答卷。" },
      { id: "low_profile", title: "低调潜伏", text: "临高的发展不算最快，却把外部风声压得很低。未来还有足够时间积蓄力量。" },
      { id: "iron", title: "铁腕百日", text: "军务和生计支撑起了秩序，代价是民望和内部空气都变得紧绷。大天使长的影子落在百仞滩上。" },
      { id: "workshop", title: "工坊路线", text: "生产能力成为百日最大的成果。工坊的火光已经亮起，但它还需要政治和民生为它供氧。" },
      { id: "civil", title: "民政优先", text: "村社、劳工和归化民愿意继续靠近临高。发展速度放慢了些，却换来了更厚的治理土壤。" },
      { id: "council", title: "会议政治", text: "元老院被稳住了，部门协同也有了章法。文德嗣保住了裁断权，但每一次推进都要付出更多协调成本。" },
    ],
    crisisCards: [
      c("CR-LIV-LOW", "all", "危机", "粮药告急", "后勤组", "仓库清单越来越薄，伤病和工程却都在要物资。再不调整，营地会先在日常中崩掉。",
        e("压缩工程配给", { livelihood: 10, council: -6, military: -4 }, 1, "保生计，伤内部"),
        e("向周边高价采购", { livelihood: 8, people: 5, wind: 5 }, 1, "补物资，露行迹"),
        ["危机", "生计"], false),
      c("CR-LIV-HIGH", "all", "危机", "过度动员", "民政组", "工坊和工程都在催进度，劳工已经连轴转。有人说再这样下去，人会先坏掉。",
        e("强制休整一天", { livelihood: -8, people: 8, council: -4 }, 1, "缓民怨，慢生产"),
        e("维持生产节奏", { livelihood: 5, military: 4, people: -10 }, 1, "保进度，压民望"),
        ["危机", "生计"], false),
      c("CR-MIL-LOW", "all", "危机", "夜间失窃", "保卫组", "仓库夜里少了工具。若只是个案，严办会伤人；若不是个案，轻放会坏规矩。",
        e("内部排查", { military: 8, council: -4, people: -3 }, 1, "查纪律，伤气氛"),
        e("公开悬赏线索", { military: 5, people: 5, livelihood: -4 }, 1, "借民望，耗物资"),
        ["危机", "军务"], false),
      c("CR-MIL-HIGH", "all", "危机", "戒严争议", "执委会", "警戒线越拉越多，口令越换越勤。几名元老开始问：我们是在建设营地，还是在建设军营？",
        e("撤下一部分岗哨", { military: -10, council: 6, people: 6 }, 1, "降军务，缓紧张"),
        e("解释后继续戒严", { military: 5, council: -8, people: -6 }, 1, "保安全，失信任"),
        ["危机", "军务"], false),
      c("CR-PEO-LOW", "all", "危机", "村社避路", "工作队", "附近村民开始绕开临高营地。没人公开对抗，但所有买卖和问话都变慢了。",
        e("派医务组登门", { people: 10, livelihood: -5, wind: 3 }, 1, "修关系，露痕迹"),
        e("暂停外出接触", { people: -4, military: 6, wind: -4 }, 1, "降风声，民望更冷"),
        ["危机", "民望"], false),
      c("CR-PEO-HIGH", "all", "危机", "请愿成风", "民政组", "各村社和劳工都学会了递条子。人人都说自己支持临高，也人人都要更多照顾。",
        e("建立公开规程", { people: -6, military: 5, council: 4 }, 1, "立规矩，降热度"),
        e("继续个案安抚", { people: 5, livelihood: -8, council: -6 }, 1, "保民望，耗资源"),
        ["危机", "民望"], false),
      c("CR-COU-LOW", "all", "危机", "元老质询", "秘书处", "几位元老联名要求解释近期裁断。若不开会，他们会认为你绕开程序。",
        e("召开说明会", { council: 12, livelihood: -5, military: -4 }, 0, "修内部，耗效率"),
        e("只发书面命令", { council: -5, livelihood: 6, military: 4 }, 0, "保速度，伤内部"),
        ["危机", "元老院"], false),
      c("CR-COU-HIGH", "all", "危机", "部门分肥", "计划组", "每个部门都拿着合理的理由来要资源。所有人都满意，百日也就什么都推不动。",
        e("重排优先级", { council: -9, livelihood: 8, military: 4 }, 1, "砍需求，推进度"),
        e("维持平衡拨款", { council: 5, livelihood: -8, people: -4 }, 1, "保内部，拖生计"),
        ["危机", "元老院"], false),
      c("CR-WIND", "all", "风声", "县里来人打听", "情报组", "县里派了不显眼的人来问港口、货物和外来人口。风声已经不只是传言。",
        e("低姿态遮掩", { wind: -8, council: -4, people: 4 }, 1, "降风声，伤内部"),
        e("展示秩序威慑", { wind: 8, military: 8, people: -6 }, 1, "强威慑，风声涨"),
        ["风声"], false),
    ],
    cards: [
      c("LG-D001", "landing", "阶段关键", "首批侦察队", "登陆指挥部", "北炜请求靠近临高角，测水深、找水源，也确认岸上是否注意到船队。",
        e("远距侦察", { military: -4, livelihood: -4, wind: -3 }, 1, "稳妥低调"),
        e("靠岸详查", { military: 5, livelihood: 6, wind: 5 }, 1, "资料充分，风声上扬"), ["登陆", "侦察"]),
      c("LG-D002", "landing", "阶段关键", "浮动码头方案", "工程组", "卸载速度跟不上，工程组要求把浮动码头列为一号工程。",
        e("安全卸载", { military: 5, livelihood: -5, council: -4 }, 1, "安全但慢", { followups: ["SER-HARBOR-1"] }),
        e("集中搭码头", { livelihood: 12, military: -6, wind: 5 }, 2, "快，但显眼", { followups: ["SER-HARBOR-2"] }), ["码头", "工程"]),
      c("LG-D003", "landing", "日常", "临高角烽烟", "侦察组", "岸上似乎有人在观察快艇。继续靠近可能惊动烽火台，退回则水文资料不足。",
        e("立刻撤回", { wind: -5, military: -4, livelihood: -4 }, 1, "降风声"),
        e("完成测绘", { livelihood: 7, military: 4, wind: 6 }, 1, "补资料"), ["侦察", "风声"]),
      c("LG-D004", "landing", "日常", "卸粮还是卸枪", "后勤组", "码头拥挤，粮药、工具和武器都等着上岸。各组都说自己的货最急。",
        e("先卸粮药", { livelihood: 10, military: -6, council: -4 }, 1, "保生存", { followups: ["LG-D005"] }),
        e("先卸武器工具", { military: 10, livelihood: -6, council: 4 }, 1, "保警戒", { followups: ["LG-D005"] }), ["卸载"]),
      c("LG-D005", "landing", "插入", "第一次内部冲突", "值班秘书", "两个元老在码头边吵了起来，一个要守流程，一个要抢进度，周围人都等你表态。",
        e("公开调停", { council: 8, livelihood: -5 }, 0, "安抚内部"),
        e("命令先干活", { livelihood: 6, council: -7, military: 4 }, 0, "压住争吵"), ["元老院"], true, { triggerOnly: true }),
      c("LG-D006", "landing", "日常", "厕所剪彩", "卫生组", "卫生组坚持先立厕所制度，否则营地很快会变成疫病温床。",
        e("低调推行", { livelihood: 6, people: 4, council: -4 }, 1, "有效但不起眼", { followups: ["SER-SANITATION-1"] }),
        e("公开立样板", { livelihood: 9, military: 4, wind: 3 }, 1, "制度化", { followups: ["SER-SANITATION-2"] }), ["卫生"]),
      c("LG-D007", "landing", "日常", "可疑的本地人", "警戒哨", "几个本地人发现了异常动静。保卫组建议控制，民政组建议安抚。",
        e("安抚放回", { people: 7, military: -5, wind: 5 }, 1, "保善意", { followups: ["SER-FIRST-CONTACT-1"] }),
        e("扣留问话", { military: 7, people: -7, wind: -3 }, 1, "控风险", { followups: ["SER-FIRST-CONTACT-2"] }), ["民望", "军务"]),
      c("LG-D008", "landing", "风声", "城里把我们当海盗", "情报组", "县城似乎把登陆者当成海贼来防。误会若发酵，风声会更乱。",
        e("派人试探", { people: 6, wind: -5, military: -4 }, 1, "解释误会"),
        e("加强警戒", { military: 7, wind: 6, people: -4 }, 1, "拒绝接触"), ["风声"]),
      c("LG-D009", "landing", "危机", "遇伏余波", "保卫组", "外出人员遭遇袭击，营地要求报复，也有人担心局势失控。",
        e("先救人封消息", { people: 6, wind: -5, military: -5 }, 1, "克制"),
        e("组织反击搜捕", { military: 11, people: -8, wind: 7 }, 1, "强硬"), ["军务"]),
      c("LG-D010", "landing", "重大行动", "博铺到百仞滩公路", "工程组", "工程组主张优先打通道路，否则港口和内陆基地无法联动。",
        e("分段慢修", { livelihood: 6, people: 5, military: -4 }, 3, "慢修"),
        e("机械化强推", { livelihood: 12, military: 5, people: -7, wind: 6 }, 5, "强推"), ["道路", "工程"]),
      c("LG-D011", "landing", "日常", "第一批俘虏", "内务组", "俘虏需要看押、喂养和安排劳动。邬德提出分化管理。",
        e("教育和翻译", { people: 7, livelihood: -5, military: -4 }, 1, "转化"),
        e("奖惩分组", { military: 7, livelihood: 5, people: -6 }, 1, "管控"), ["俘虏"]),
      c("LG-D012", "landing", "日常", "小灵通网络", "通信组", "通信组想架设营地内无线通信。设备不多，拿出来就难免损耗。",
        e("留作应急", { military: -5, livelihood: -4, council: 5 }, 1, "保设备"),
        e("铺开试用", { military: 6, livelihood: 5, council: -5 }, 1, "提效率"), ["通信"]),
      c("LG-S001", "foothold", "阶段关键", "第一次反围剿", "军事组", "地方武装和误判的敌意终于撞上来了。营地必须形成战斗秩序。",
        e("守住营地", { military: 7, people: 5, wind: -4, livelihood: -5 }, 1, "稳守", { followups: ["SER-COUNTER-1"] }),
        e("打散来敌", { military: 12, livelihood: 5, people: -8, wind: 7 }, 1, "震慑", { followups: ["SER-COUNTER-2"] }), ["战斗"]),
      c("LG-S002", "foothold", "阶段关键", "战后扩大会议", "执委会", "战斗结束后，元老们要求复盘。有人追问警戒漏洞，有人要求扩大军事授权。",
        e("开放检讨", { council: 10, military: -5, livelihood: -5 }, 0, "程序优先"),
        e("直接整改", { military: 7, livelihood: 6, council: -7 }, 0, "效率优先"), ["会议"]),
      c("LG-S003", "foothold", "日常", "砖瓦木炭", "工业组", "基础建材不能再等。工业组要求抽调劳力烧砖、烧炭。",
        e("保开荒劳力", { people: 5, livelihood: -6, council: -4 }, 1, "保农事"),
        e("优先建材", { livelihood: 11, people: -6, council: 5 }, 1, "保工程"), ["工业"]),
      c("LG-S004", "foothold", "日常", "临高快讯", "宣传组", "宣传组建议发行营地快讯，统一口径、传播战果。",
        e("内部简报", { council: 5, wind: -4, people: -3 }, 1, "低调"),
        e("公开发行", { council: 8, people: 5, wind: 6 }, 1, "鼓舞人心"), ["宣传"]),
      c("LG-S005", "foothold", "阶段关键", "百仞城选址", "建筑组", "百仞滩将成为新基地。行政区、水电区、工坊区如何先建，争议很大。",
        e("先建住区卫生", { people: 7, livelihood: 6, council: -5 }, 3, "民生优先"),
        e("先建行政工坊", { council: 6, livelihood: 11, people: -6 }, 3, "建设优先"), ["城市"]),
      c("LG-S006", "foothold", "日常", "供水系统", "工程组", "供水站能减少病患；材料留给工坊，短期产出更快。",
        e("先保饮水", { people: 7, livelihood: 6, council: -4 }, 1, "卫生"),
        e("材料给工坊", { livelihood: 10, people: -7 }, 1, "产出"), ["供水"]),
      c("LG-S007", "foothold", "日常", "代水泥实验", "王洛宾", "真正水泥条件不足，王洛宾提出先用代水泥。工程组担心强度。",
        e("小规模验证", { livelihood: 5, council: 4 }, 1, "谨慎"),
        e("用于低强度工程", { livelihood: 10, council: -5, people: -4 }, 1, "冒进"), ["建材"]),
      c("LG-S008", "foothold", "日常", "俘虏夜课", "教育组", "俘虏开始学习普通话。有人建议投入教师，有人认为先让他们干活。",
        e("安排夜课", { people: 7, livelihood: -5, military: -4 }, 1, "教化"),
        e("劳动优先", { livelihood: 6, military: 5, people: -6 }, 1, "效率"), ["教育"]),
      c("LG-S009", "foothold", "日常", "警戒住宿制度", "保卫组", "保卫组建议每个宿舍配置武器并定期操练。民政组担心误伤。",
        e("集中武器管理", { people: 5, military: -6, council: 5 }, 1, "谨慎"),
        e("宿舍配发武器", { military: 10, people: -6, council: -4 }, 1, "备战"), ["军务"]),
      c("LG-S010", "foothold", "风声", "临高议和试探", "外事组", "县里有人愿意探一探口风。谈得好能缓和误会，谈砸会更显眼。",
        e("低姿态谈判", { people: 8, wind: -7, council: -5 }, 1, "缓和"),
        e("展示实力", { military: 7, council: 5, wind: 7 }, 1, "威慑"), ["外事"]),
      c("LG-S011", "foothold", "阶段关键", "南海示范农庄", "吴南海", "农业组提出建立示范农庄，用产量和伙食吸引本地人。",
        e("小规模试办", { people: 7, livelihood: 5, council: -4 }, 2, "试办"),
        e("集中办样板", { people: 11, livelihood: 6, military: -5 }, 3, "样板"), ["农业"]),
      c("LG-S012", "foothold", "危机", "配给标准争议", "后勤组", "元老、技术人员、劳工和俘虏的配给标准是否拉开，会议吵得很厉害。",
        e("尽量一视同仁", { people: 8, council: -7, livelihood: -6 }, 1, "公平"),
        e("按岗位分级", { livelihood: 7, council: 7, people: -8 }, 1, "效率"), ["配给"]),
      c("LG-B001", "build", "阶段关键", "工分制度", "邬德", "原有劳动安排开始失灵。邬德建议用工分重新绑定劳动和待遇。",
        e("温和试行", { people: 6, council: 5, livelihood: -5 }, 2, "试行"),
        e("全面推行", { livelihood: 12, military: 5, people: -7 }, 2, "制度化", { followups: ["SER-WORKPOINT-1"] }), ["制度"]),
      c("LG-B002", "build", "阶段关键", "释放俘虏讨论", "执委会", "俘虏是否释放回家引发争论。放走有利于善意，也可能泄露情报。",
        e("择优释放", { people: 11, wind: 6, military: -6 }, 0, "善意"),
        e("继续管理", { military: 7, wind: -5, people: -7, council: -4 }, 0, "保密"), ["俘虏"]),
      c("LG-B003", "build", "重大行动", "第一次黎区探险", "外事组", "山地那边出现联络可能。亲自带队能打开局面，也会让营地承受风险。",
        e("派小队接触", { people: 7, wind: -4, council: -4 }, 3, "谨慎", { followups: ["SER-LI-1"] }),
        e("文德嗣带队", { people: 12, council: 6, military: -6, wind: 5 }, 5, "亲自裁断", { followups: ["SER-LI-2"] }), ["黎区"]),
      c("LG-B004", "build", "阶段关键", "盐场村工作队", "工作队", "盐场村可以成为基层治理样板，但工作队要求更多干部、药品和宣传物资。",
        e("医疗和交易先行", { people: 8, wind: -4, livelihood: -5 }, 2, "柔性接触"),
        e("直接组织基层", { people: 11, council: 5, wind: 6 }, 2, "组织化"), ["基层"]),
      c("LG-B005", "build", "插入", "私人流言", "秘书处", "几名元老的私人交往被人议论。事情不大，但若放任流言，会损害纪律。",
        e("私下提醒", { council: 5, military: -3 }, 0, "留余地"),
        e("公开立规矩", { military: 6, council: -5, people: -3 }, 0, "立纪律"), ["元老院"], true, { triggerOnly: true }),
      c("LG-B006", "build", "日常", "铵木炸药实验", "化工组", "爆破材料有进展。军务组要求配发，工程组想拿来开山取石。",
        e("给工程试用", { livelihood: 10, military: -5, council: -4 }, 1, "工程"),
        e("军务储备", { military: 10, livelihood: -5, wind: 5 }, 1, "军务"), ["军工"]),
      c("LG-B007", "build", "重大行动", "攻打苟家庄", "军务组", "苟家庄成了不稳定源。主动出击可震慑地方，但伤亡和风声难免。",
        e("围困施压", { people: 5, wind: -4, military: -6, council: -4 }, 2, "克制", { followups: ["SER-GOU-1"] }),
        e("批准攻打", { military: 12, livelihood: 6, people: -9, wind: 10 }, 3, "出击", { followups: ["LG-B008", "SER-GOU-2"] }), ["战斗"]),
      c("LG-B008", "build", "插入", "第一例牺牲", "秘书处", "战斗胜利了，但穿越者第一次付出了生命代价。营地需要一个说法。",
        e("低调抚恤", { council: 6, people: -4, military: -4 }, 0, "压住"),
        e("公开悼念", { council: 9, military: 5, wind: 5 }, 0, "立碑"), ["牺牲"], true, { triggerOnly: true }),
      c("LG-B009", "build", "重大行动", "广州先遣", "商业组", "广州行能打开贸易和情报窗口，但远距离行动会带来暴露风险。",
        e("低调商队", { livelihood: 6, wind: 5, council: -4 }, 3, "低调", { followups: ["SER-GZ-1"] }),
        e("建立先遣站", { livelihood: 12, council: 5, wind: 10 }, 5, "扩张", { followups: ["SER-GZ-2"] }), ["贸易"]),
      c("LG-B010", "build", "日常", "东门市", "商业组", "交易越来越多，临时摊点需要变成市场。市场能吸粮，也会吸来眼睛。",
        e("限制规模", { wind: -5, military: 5, livelihood: -6 }, 1, "控风险"),
        e("正式设市", { livelihood: 10, people: 6, wind: 6 }, 1, "活市场"), ["市场"]),
      c("LG-B011", "build", "日常", "妇女合作社", "民政组", "李梅提出组织妇女合作社，把纺织、后勤和安置结合起来。",
        e("后勤小组起步", { people: 6, livelihood: 5, council: -4 }, 1, "稳妥"),
        e("公司化运作", { livelihood: 10, council: 5, people: -5 }, 1, "制度化"), ["合作社"]),
      c("LG-B012", "build", "危机", "技术保密", "安全组", "本地工匠已经学会不少做法。技术组兴奋，安全组紧张。",
        e("传授低阶工艺", { livelihood: 7, people: 6, wind: 5 }, 1, "扩生产"),
        e("划定保密等级", { military: 6, wind: -5, people: -6 }, 1, "保安全"), ["保密"]),
      c("LG-T001", "stable", "阶段关键", "初期工作总结", "计划组", "百日过半，会议要求总结路线。有人主张先军，有人主张民政，有人盯着生产。",
        e("折中报告", { council: 7, people: 5, livelihood: -5 }, 0, "平衡"),
        e("优先军工生产", { military: 7, livelihood: 7, council: -6, people: -6 }, 0, "定路线"), ["总结"]),
      c("LG-T002", "stable", "阶段关键", "劳工制度二改", "制度组", "工分制度有效，但漏洞也多。是否把劳工、雇工、俘虏、助理分层管理？",
        e("弱化身份差异", { people: 10, council: -6, livelihood: -6 }, 2, "平等"),
        e("明确分层管理", { livelihood: 7, military: 7, people: -8 }, 2, "秩序"), ["制度"]),
      c("LG-T003", "stable", "日常", "东门市派出所", "治安组", "东门市人流复杂，偷盗、斗殴和投机开始出现。治安组要求设派出所。",
        e("市场自治", { people: 6, military: -7, wind: -4 }, 1, "自治"),
        e("成立派出所", { military: 10, people: -6, livelihood: 5 }, 1, "管控"), ["治安"]),
      c("LG-T004", "stable", "阶段关键", "临高角海战", "海防组", "海上威胁不再是纸面推演。诸彩老部的船影已经出现。",
        e("守港驱离", { military: 7, wind: -4, livelihood: -5 }, 1, "守势", { followups: ["LG-T005"] }),
        e("主动截击", { military: 12, council: 5, wind: 10 }, 1, "主动", { followups: ["LG-T005"] }), ["海战"]),
      c("LG-T005", "stable", "插入", "武器问题暴露", "军务组", "海战打赢了，但武器问题暴露得很清楚。军务组要求立刻调整资源。",
        e("修补现有武器", { military: 6, livelihood: -4 }, 0, "修补"),
        e("启动军工链条", { military: 10, livelihood: 6, people: -5, council: -5 }, 0, "扩军工"), ["军工"], true, { triggerOnly: true }),
      c("LG-T006", "stable", "日常", "简易船坞", "船务组", "船只维护不能继续靠临时办法。船坞会占用木材、工匠和码头空间。",
        e("先修滑道", { livelihood: 5, military: -5 }, 2, "临时"),
        e("建简易船坞", { military: 6, livelihood: 10, people: -5 }, 2, "长期"), ["船坞"]),
      c("LG-T007", "stable", "日常", "炼钢上马", "工业组", "炼钢终于排上日程。缺煤、缺矿、缺熟练工，所有问题都在催你拍板。",
        e("小炉试验", { livelihood: 6, council: 4, military: -4 }, 2, "试验"),
        e("集中攻关", { livelihood: 11, military: 5, people: -6, wind: 5 }, 2, "攻关"), ["炼钢"]),
      c("LG-T008", "stable", "日常", "铸炮争议", "军工组", "军工组要求尽快试铸火炮。工匠说炉子还没摸熟，军务组说等不起。",
        e("小件练手", { livelihood: 5, military: -5, council: 5 }, 1, "稳"),
        e("直接试炮", { military: 10, livelihood: -6, wind: 6 }, 1, "快"), ["火炮"]),
      c("LG-T009", "stable", "风声", "谈判还是备战", "计划委员会", "有人建议与海上势力谈判换取时间；也有人认为示弱会引来勒索。",
        e("秘密接触", { wind: -7, military: -5, livelihood: 5 }, 1, "谈"),
        e("拒谈备战", { military: 8, council: 5, wind: 6 }, 1, "战"), ["外事"]),
      c("LG-T010", "stable", "阶段关键", "新军筹备", "军事组", "只靠穿越者巡逻作战太浪费。新军方案要求把本地士兵训练成骨干。",
        e("先办教导队", { military: 7, people: 5, livelihood: -5 }, 3, "试办", { followups: ["SER-NEWARMY-1"] }),
        e("改革军委", { military: 12, council: -7, people: -7 }, 3, "重组", { followups: ["SER-NEWARMY-2"] }), ["新军"]),
      c("LG-T011", "stable", "日常", "炸药生产线", "化工组", "实验室成果要不要转为生产线？安全事故、保密和原料都成问题。",
        e("小批量", { military: 5, livelihood: -5, wind: -3 }, 1, "谨慎"),
        e("扩大生产", { military: 10, livelihood: 5, people: -6, wind: 6 }, 1, "生产"), ["炸药"]),
      c("LG-T012", "stable", "日常", "线膛枪和米尼弹", "军工组", "枪械组提出试制线膛枪和配套弹药。资源一旦给出去，民生工程会慢下来。",
        e("技术储备", { council: 5, livelihood: 5, military: -6 }, 2, "储备"),
        e("立刻试制", { military: 12, livelihood: -6, wind: 6 }, 2, "试制"), ["枪械"]),
      c("LG-T013", "stable", "阶段关键", "新军政治工作", "政工组", "新军不能只是会操枪的人。政工组要求建立忠诚教育和政治工作。",
        e("待遇纪律为主", { people: 6, military: 6, council: -4 }, 1, "务实"),
        e("建立政工体系", { military: 10, council: 5, people: -5 }, 1, "体系化"), ["政工"]),
      c("LG-T014", "stable", "总结前", "百日前夜质询", "执委会", "百日将近，元老们要求你说明：这是临时避险，还是新政权的开端？",
        e("强调临时执政", { council: 7, wind: -6, military: -5 }, 0, "低调"),
        e("承认长期建设", { livelihood: 7, military: 7, wind: 6, council: -6 }, 0, "定调"), ["总结"]),

      c("SP-001", "all", "特殊", "夜半急报", "值夜室", "深夜送来的条子没有署名，只说仓库、码头和警戒线都有小问题。你可以立刻查，也可以等天亮。",
        e("天亮再查", { council: 4, military: -4, livelihood: -3 }, 1, "不扰众"),
        e("立刻点人", { military: 6, council: -4, people: -3 }, 0, "马上处理"), ["特殊", "夜间"]),
      c("SP-002", "all", "特殊", "文德嗣签发令", "秘书处", "几份命令卡在部门之间，谁都说自己没错。只要你签字，事情会立刻动起来。",
        e("退回会签", { council: 6, livelihood: -5, military: -3 }, 0, "程序"),
        e("直接签发", { livelihood: 6, military: 4, council: -7 }, 0, "裁断", { followups: ["LG-B005"] }), ["特殊", "元老院"]),
      c("SP-003", "all", "特殊", "临时配给券", "后勤组", "有人建议发行临时配给券，把混乱的领取制度先管起来。商业组担心这会变成另一个账本地狱。",
        e("先记实物账", { livelihood: -4, council: 5, people: 4 }, 1, "慢但清楚"),
        e("发行配给券", { livelihood: 7, council: -5, people: -3 }, 1, "快但粗"), ["特殊", "后勤"]),
      c("SP-004", "all", "特殊", "翻译不够用", "外事组", "外部接触越来越多，真正能听懂、说清、还守纪律的翻译却没几个。",
        e("培养本地通事", { people: 7, wind: 4, livelihood: -4 }, 1, "打通外部"),
        e("翻译集中管制", { military: 5, wind: -4, people: -5 }, 1, "保密优先"), ["特殊", "外事"]),
      c("SP-005", "all", "特殊", "档案编号", "档案室", "秘书处要求所有命令、会议、物资调拨都统一编号。没人反对，只是人人都嫌麻烦。",
        e("只管重要文件", { council: 4, livelihood: -3 }, 1, "轻量"),
        e("全面建档", { council: 7, livelihood: -5, military: 3 }, 1, "制度化", { followups: ["SER-ARCHIVE-1"] }), ["特殊", "档案"]),
      c("SP-006", "all", "特殊", "台风边缘", "气象组", "海面气压不太对。气象组建议提前收拢船只和物资，工程组认为这会拖慢进度。",
        e("按预案收拢", { military: 5, livelihood: -5, wind: -2 }, 2, "避险"),
        e("继续抢工", { livelihood: 7, military: -7, people: -4 }, 1, "抢时间"), ["特殊", "天气"]),
      c("SP-007", "all", "特殊", "元老家书", "通信组", "有人提出整理一批不能寄出的家书，作为心理疏导。也有人觉得这只会让大家更想旧世界。",
        e("允许写入档案", { council: 6, people: 3, livelihood: -3 }, 0, "安抚"),
        e("暂缓此事", { military: 3, council: -5, livelihood: 3 }, 0, "压住情绪"), ["特殊", "心理"]),
      c("SP-008", "all", "特殊", "旧世界知识课", "教育组", "几个年轻劳工对旧世界机器和制度很感兴趣。教育组想开公开课，安全组皱着眉头。",
        e("讲基础卫生和算术", { people: 6, livelihood: 4, wind: 2 }, 1, "低阶知识"),
        e("严格限制内容", { military: 4, wind: -4, people: -5 }, 1, "保密"), ["特殊", "教育"]),
      c("SP-009", "all", "特殊", "酒精用途", "医疗组", "有限的酒精既能消毒，也能安抚疲惫的元老和技术员。每个人都有理由。",
        e("全部归医疗", { livelihood: 7, council: -5, people: 2 }, 1, "医疗优先"),
        e("留少量慰劳", { council: 6, livelihood: -5, military: -3 }, 1, "安抚内部"), ["特殊", "医疗"]),
      c("SP-010", "all", "特殊", "流言版地图", "情报组", "有人把临高周边传言画成了一张粗糙地图。真假难辨，但能看出谁在怕谁。",
        e("交外事组核实", { people: 5, wind: 3, military: -3 }, 1, "走访"),
        e("交保卫组研判", { military: 5, wind: -3, people: -3 }, 1, "安全"), ["特殊", "情报"]),

      c("SER-HARBOR-1", "landing", "系列", "卸载队怨言", "码头值班员", "安全卸载确实少出事故，但码头边排队的人越来越烦躁。有人开始说工程组太保守。",
        e("增设夜班", { livelihood: 5, military: -4, people: -3 }, 1, "赶进度"),
        e("维持日班", { military: 4, livelihood: -5, council: -3 }, 1, "保安全"), ["系列", "码头"], true, { triggerOnly: true }),
      c("SER-HARBOR-2", "landing", "系列", "木排断缆", "工程组", "浮动码头抢出来了，临时绳缆却在涨潮时断了一截。现在要决定追责还是补救。",
        e("先补救", { livelihood: 5, council: -4, military: -3 }, 0, "救工程"),
        e("现场追责", { military: 5, council: 3, people: -4 }, 0, "立规矩"), ["系列", "码头"], true, { triggerOnly: true }),
      c("SER-SANITATION-1", "landing", "系列", "厕所旁的告示", "卫生组", "低调卫生令贴出去后，很多人看不懂或装看不懂。卫生组请求配人盯守。",
        e("派人讲解", { people: 5, livelihood: 4, council: -3 }, 1, "讲规矩"),
        e("抓典型处罚", { military: 5, livelihood: 3, people: -5 }, 1, "严执行"), ["系列", "卫生"], true, { triggerOnly: true }),
      c("SER-SANITATION-2", "landing", "系列", "剪彩后的笑话", "秘书处", "厕所剪彩成了营地笑话，但大家也确实记住了卫生制度。要不要顺势搞一次卫生竞赛？",
        e("顺势办竞赛", { livelihood: 5, people: 4, council: -4 }, 1, "借势"),
        e("到此为止", { council: 3, livelihood: -3 }, 0, "收住"), ["系列", "卫生"], true, { triggerOnly: true }),
      c("SER-FIRST-CONTACT-1", "landing", "系列", "被放回的人", "外事组", "被放回的本地人带来了更多好奇者。他们不敢靠近，只在远处张望。",
        e("送水和盐", { people: 6, livelihood: -4, wind: 3 }, 1, "示善"),
        e("保持距离", { wind: -3, military: 3, people: -4 }, 1, "低调"), ["系列", "接触"], true, { triggerOnly: true }),
      c("SER-FIRST-CONTACT-2", "landing", "系列", "问话口供", "保卫组", "扣留者说县城已经有人听见海上动静。保卫组要求延长扣留，外事组建议尽快放人。",
        e("尽快放人", { people: 5, military: -4, wind: 4 }, 0, "缓和"),
        e("延长扣留", { military: 6, wind: -3, people: -6 }, 0, "控口风"), ["系列", "接触"], true, { triggerOnly: true }),
      c("SER-COUNTER-1", "foothold", "系列", "守势后的轻视", "军事组", "守住营地后，部分元老认为地方武装不过如此。保卫组担心轻敌。",
        e("维持警戒等级", { military: 5, council: -3, livelihood: -3 }, 1, "不松劲"),
        e("释放部分警戒人手", { livelihood: 5, council: 3, military: -5 }, 1, "回生产"), ["系列", "反围剿"], true, { triggerOnly: true }),
      c("SER-COUNTER-2", "foothold", "系列", "俘虏的恐惧", "民政组", "反击很成功，俘虏也很害怕。恐惧能带来服从，也会让外部把临高想得更可怕。",
        e("安抚俘虏", { people: 6, military: -4, wind: -2 }, 1, "降恐惧"),
        e("保持震慑", { military: 6, people: -5, wind: 4 }, 1, "立威"), ["系列", "反围剿"], true, { triggerOnly: true }),
      c("SER-WORKPOINT-1", "build", "系列", "工分作弊", "制度组", "工分制度刚推开，就有人虚报、互相顶名。制度若不修，威信会掉得很快。",
        e("建立复核员", { military: 4, livelihood: 5, people: -4 }, 1, "查账", { followups: ["SER-WORKPOINT-2"] }),
        e("先不扩大化", { people: 4, council: -4, livelihood: -5 }, 1, "压住"), ["系列", "工分"], true, { triggerOnly: true }),
      c("SER-WORKPOINT-2", "build", "系列", "复核员也要吃饭", "后勤组", "复核员制度能管住账，但也占人、占粮、占纸。有人开始抱怨制度越来越重。",
        e("保留精简版", { livelihood: 3, council: 4, people: -3 }, 1, "精简"),
        e("继续加密复核", { military: 4, livelihood: -4, council: -3 }, 1, "严管"), ["系列", "工分"], true, { triggerOnly: true }),
      c("SER-LI-1", "build", "系列", "山路回信", "外事组", "小队带回了山里的回信。对方愿意见面，但要求临高先拿出诚意。",
        e("带药品去", { people: 7, livelihood: -5, wind: 2 }, 2, "医药示好"),
        e("带工具去", { people: 5, livelihood: -3, council: 3 }, 2, "实用交换"), ["系列", "黎区"], true, { triggerOnly: true }),
      c("SER-LI-2", "build", "系列", "文德嗣不在营地", "秘书处", "你亲自带队外出，营地里几项事务临时积压。秘书处请求扩大代理权限。",
        e("授权代理", { council: 5, livelihood: 3, military: -4 }, 0, "信任"),
        e("远程裁断", { military: 3, council: -5, livelihood: -4 }, 0, "掌控"), ["系列", "黎区"], true, { triggerOnly: true }),
      c("SER-GOU-1", "build", "系列", "苟家庄拖延", "军务组", "围困让局势暂时冷下来，但苟家庄也在等临高露出疲态。军务组要求增加压力。",
        e("继续谈判", { people: 5, wind: -3, military: -5 }, 1, "拖"),
        e("夜间演训", { military: 7, wind: 4, livelihood: -3 }, 1, "压"), ["系列", "苟家庄"], true, { triggerOnly: true }),
      c("SER-GOU-2", "build", "系列", "战利品清点", "后勤组", "苟家庄缴获能补仓库，也能作为政治宣传。怎么分配，决定大家记住的是什么。",
        e("优先入库", { livelihood: 8, council: -3, people: -3 }, 1, "补仓"),
        e("公开分配一部分", { people: 6, council: 4, livelihood: -5, wind: 3 }, 1, "收心"), ["系列", "苟家庄"], true, { triggerOnly: true }),
      c("SER-GZ-1", "build", "系列", "商队带回的价目", "商业组", "低调商队带回了广州物价，也带回了对临高货物的好奇。商业组想扩大采买。",
        e("只买必需品", { livelihood: 4, wind: -3, council: -3 }, 1, "克制"),
        e("扩大采买清单", { livelihood: 8, council: 3, wind: 5 }, 2, "扩张"), ["系列", "广州"], true, { triggerOnly: true }),
      c("SER-GZ-2", "build", "系列", "先遣站口径", "商业组", "广州先遣站需要一个对外身份。说成商号最稳，说成海外背景最能唬人。",
        e("普通商号", { wind: -4, people: 3, livelihood: -3 }, 1, "低调"),
        e("海外奇货", { livelihood: 7, wind: 7, council: 4 }, 1, "吸引"), ["系列", "广州"], true, { triggerOnly: true }),
      c("SER-NEWARMY-1", "stable", "系列", "教导队第一课", "教导队", "第一批本地兵站得很直，但他们更关心饭、饷和家里人。政治口号暂时不如实物有用。",
        e("先讲待遇", { people: 5, military: 4, livelihood: -4 }, 1, "现实"),
        e("先讲纪律", { military: 7, people: -4, council: 3 }, 1, "纪律"), ["系列", "新军"], true, { triggerOnly: true }),
      c("SER-NEWARMY-2", "stable", "系列", "军委改组反弹", "秘书处", "军委改革触动了不少元老的岗位和面子。有人说新军还没成，官僚机器先成了。",
        e("设过渡期", { council: 6, military: -4, livelihood: -3 }, 1, "缓冲"),
        e("按新章程执行", { military: 7, council: -7, people: -3 }, 1, "硬推"), ["系列", "新军"], true, { triggerOnly: true }),
      c("SER-ARCHIVE-1", "all", "系列", "旧命令翻案", "档案室", "档案员翻出一份前后不一致的命令。承认错误会伤威信，掩过去又会伤制度。",
        e("承认并修正", { council: 5, people: 3, military: -4 }, 0, "修正"),
        e("按当时情况解释", { military: 4, council: -4, people: -3 }, 0, "维护威信"), ["系列", "档案"], true, { triggerOnly: true }),
    ],
  };
})();
